### ISSUE TITLE
Adding templates for MvcScaffolding

### ISSUE THREAD

**Issue by tikrimi** [erichexter/twitter.bootstrap.mvc#34]
Hi,

I'm using a lot the MvcScaffolding package.
Currently, when I add a controller, I need to change the Inheritance, and add a parameter in the Create view.
 Do you thing that is a good idea to add a dependence to the MvcScaffolding package and add templates for scaffolding a controller with  a context and with a repository ?

**Comment by erichexter** [comment]
I would make this a seperate package in the twitter.bootstrap.mvc4 space.
Say .scaffolding ? Since it is oppionated aboutthe data access i would like
to maintain itin a seperate repository or under a seperate folder in this
repository.  Since diiferent data access patterns are appropriate for
different scale of applications.

**Comment by serra** [comment]
+1  for this feature 
+1 for the separate package

**Comment by tikrimi** [comment]
I have fork the mvcscaffolding project on GitHub and adding the -TwitterBootstrapMvc flag in order to support the creation of "twitter.bootstrap.mvc4" controllers.
You can find the result here : https://github.com/tikrimi/MvcScaffolding4TwitterBootstrapMvc.
For creating scaffolding for a controller creating use:

> Scaffold Controller {your_model} -TwitterBootstrapMvc

It create a controller based on the HomeController that you can find in the twitter.bootstrap.mvc4.sample.
