### ISSUE TITLE
Build errors after installing the package

### ISSUE THREAD

**Issue by fernandoacorreia** [erichexter/twitter.bootstrap.mvc#6]
After installing the package, you may get build errors.
1. Compiling transformation: The type or namespace name 'Web' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?) 
2. Compiling transformation: The type or namespace name 'MvcTextTemplateHost' could not be found (are you missing a using directive or an assembly reference?) 

These errors are resolved by closing and reopening the solution.

Verified in Visual Studio 2010 and 2012.

**Comment by erichexter** [comment]
This is a known issue and documented in the readme.  There is no resolution to this, at this time.

**Comment by fernandoacorreia** [comment]
All right. Thanks.

**Comment by FieldMarshallVague** [comment]
If your solution can't find System.Web.Mvc, install the package for it via NugGet.  Here's a link to that package's homepage.. simple install via nuget package manager console.

http://nuget.org/packages/AspNetMvc/

FYI, the correct install order (at time of writing) is:
1. Create new web app project (.Net 4.5). Delete the homecontroller.cs and _viewstart.cshtml, otherwise these won't be overwritten in the next steps.
2. install-package twitter.bootstrap.mvc4.sample (in PM Console)
3. install-package twitter.bootstrap.mvc4
4. install-package apsnetmvc
