### ISSUE TITLE
Paging issue with active page

### ISSUE THREAD

**Issue by maroquio** [erichexter/twitter.bootstrap.mvc#80]
The Pager helper function have an error on line 61. The correct code should be:

if (i == (currentPage))
...

But this is awsome!
Regards!

**Comment by serra** [comment]
Thanks for reporting, I'll check it out.

**Comment by serra** [comment]
@maroquio - I think there is no error. The `IPagedList` model uses a zero-based `PageIndex`, so it was convenient for the `currentPage` argument of `MvcHtmlString Pager` to be zero-based too.

I admit that this might be a bit confusing, since the `ToPagedList<T>` takes a one-based page argument, so that we can immediately pass in the page parameter we get from the request.

I created a small sample project that adds paging to the sample app: [1](https://github.com/serra/promo/commit/05c23a64d3833a1107cd24ea642239794cc5345f) | [2](https://github.com/serra/promo/commit/b02328c3feac2b93b9105be59eeaf055156017b3) | [3](https://github.com/serra/promo/commit/894bebcf7a4b1b2f2ff2df51b0cceff4ae8ffaca) | [4](https://github.com/serra/promo/commit/cbb0dcff86c7a8544ff5b0a9d5dbfed4f4f49461) | [5](https://github.com/serra/promo/commit/6c24db2710564955cd7ecb7d509854920d55a3c9)

Please let me know if you still think there's a bu there.

**Comment by maroquio** [comment]
Hi, Serra. While I was testing, I've tried 0-based index using, but I had to do some arithmetics on the GUI to make it work correctly. It was really confusing. I'm not sure if it is a good idea to keep it like that, but if it works well as 0-based index, its everything allright. Anyway, thanks for your answer and for keeping this very useful project.

**Comment by serra** [comment]
Glad you worked it out, I agree it can be a bit confusing. Feel free to suggest some changes in a pull request. It would indeed be better if the full public api of the paged list implementation used the same base for the page index.

**Comment by serra** [comment]
@maroquio - could you close this bug report? Thanks.

**Comment by maroquio** [comment]
Done!
Regards.

2013/3/12 Marijn van der Zee notifications@github.com
